# First Functions


In [ ]:
#A funtion to determine if a number is even or odd
def parser(num):
  print(num)
  if num%2==0:
    print("even")
  else:
    print("odd")

# passing value to a function using loops
for i in range(5):
  val = int(input("enter the number you want to check"))
  parser(val)

In [ ]:
#Example of a recursive function

def factorial(n):
  if n>1:
    return n*factorial(n-1)
  elif n==1:
    return 1
f = factorial(5)
print(f)

# Numpy

In [4]:
#simple example of transposing a matrix using numpy
import numpy as np
a = np.arange(15).reshape(3,5)
p = np.dot(a,a.T)
print("matrix a is \n", a,a.shape)
print("matrix a is \n", a.T,a.T.shape)

matrix a is 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] (3, 5)
matrix a is 
 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]] (5, 3)


# Pandas

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', None)
df_auto = pd.read_csv('automobil.csv')
print(df_auto.info())

In [ ]:
df_auto.info()

In [ ]:
df_auto.loc[:,['gas','diesel','horsepower-binned']]

In [ ]:
df_auto.loc[2,'gas']

In [ ]:
df_auto['symboling'].max()
df_auto['symboling'].min()

-2

In [ ]:
df_auto.describe()

In [ ]:
df_auto.head()

In [ ]:
df_auto.tail()

In [ ]:
pd.crosstab(df_auto['bore'], columns='count')

In [ ]:
df_auto['symboling'].value_counts().plot.bar()

# Exploratory Data Analysis

In [10]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
sns.set(rc = {'figure.figsize':(12,9)})

In [ ]:
cars_data = pd.read_csv('cars_sampled.csv')


In [ ]:
# create a copy
cars = cars_data.copy()

In [ ]:
print(cars)

In [ ]:
cars.info()


In [ ]:
cars.describe()

In [ ]:
pd.set_option('display.float_format',lambda x: '%.3f' %x)

In [ ]:
cars['price'].describe()

In [ ]:
#drop unwanted columns
cols = ['name', 'dateCrawled', 'dateCreated', 'postalCode','lastSeen']
cars = cars.drop(columns=cols,axis=1)

# Data Wrangle

In [2]:
# merge or join operation
from pandas import DataFrame
df1 = DataFrame({'key':['x','y','z','m','n'],'data':range(5)})
print(df1)

  key  data
0   x     0
1   y     1
2   z     2
3   m     3
4   n     4


In [ ]:
df2 = DataFrame({'key':['x','y','z','dx'],'data':range(4)})

In [ ]:
df2

In [ ]:
pd.merge(df1,df2,on='key')

In [ ]:
pd.merge(df1,df2,how='outer')

In [5]:
lefth = DataFrame({'key1': ['Ohio', 'Ohio','Ohio', 'Nevada', 'Nevada'],
                   'key2': [2000,2001,2002,2001,2002],
                   'data': np.arange(5,)})

In [ ]:
print(lefth)

In [8]:
righth = DataFrame(np.arange(12).reshape((6,2)),
index=[['Nevada', 'Nevada','Ohio', 'Ohio','Ohio','Ohio'],
[2001, 2000, 2000, 2000,2001,2002]], columns=['event1', 'event2'] )

In [ ]:
print(righth)

In [ ]:
pd.merge(lefth, righth, left_on=['key1','key2'], right_index=True)

# Data Transformation

In [14]:
dataa = DataFrame({'k1': ['one'] * 3 + ['two']*4,
                   'k2': [1,1,2,3,3,4,4]})

In [15]:
print(dataa)

    k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4


In [16]:
dataa.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [17]:
dataa.drop_duplicates()

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

# Bringing it all together

In [18]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
sns.set(rc = {'figure.figsize':(12,9)})

In [22]:
path = "/content/drive/MyDrive/cars_sampled.csv"
cars_data = pd.read_csv(path)

In [23]:
# create a copy
cars = cars_data.copy()

In [ ]:
print(cars)